#page title
page_title                                : SimpleBooking                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : gb                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SimpleBooking                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Lets small events organise themselves.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mechanical Man Dev
your_link                                 : https://mechanicalman.dev                     
your_city                                 : Bristol                                
email_address                             : mechanicalmandev@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Manage Attendance for Informal Events
    description                           : Ideal for managing weekly local events which usually draw on a base of regular attendees.
    fontawesome_icon_name                 : users
    
  - title                                 : Manage Waitlists
    description                           : Once events fill up further bookings go into a waitlist with notifications when others cancel. 
    fontawesome_icon_name                 : list-alt
    
  - title                                 : Track Payments
    description                           : Enter payments details so that you and the attendees can see what has been paid for.
    fontawesome_icon_name                 : money-bill-wave-alt

  - title                                 : Limit Bookings
    description                           : Limit the number of confirmed bookings a user can have so that everyone gets a chance.
    fontawesome_icon_name                 : arrow-down
    
  - title                                 : Quickly See Upcoming Bookings
    description                           : Each user can see a list of all events and can easily see which ones they have booked.
    fontawesome_icon_name                 : eye

  - title                                 : Record of Past Attendance
    description                           : Access past events to see who attended, shows payments on past events.
    fontawesome_icon_name                 : archive

  - title                                 : Keeps Contact Details
    description                           : Hold the contact details of your attendees for quick contact if the event is cancelled or changes.
    fontawesome_icon_name                 : id-card

  - title                                 : Regular Plus Ones
    description                           : Each booking specifies a guest of the attendee.  Each user can have a list of regular guests.
    fontawesome_icon_name                 : user-plus

  - title                                 : Self Serve Cancellations
    description                           : Users can cancel bookings themselves and anyone on waiting list notified of the space.
    fontawesome_icon_name                 : window-close



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
